X916 - enhance cDNA anaylsis page
sanger/stan-client pull request #208
Opened 2022-08-25 12:39 UTC by BenTopping

Closes #202 

Changes proposed in this pull request:

* Visium QC 'cDNA Analysis' option has been renamed to 'cDNA concentration' and 'Library concentration' option has been added
* Visium QC 'cDNA concentration' and 'Library concentration' have the ability to add comments to each slot
* Config now contains new 'Comments - concentration' for editing comments related to Visium QC 'cDNA concentration' and 'Library concentration'

2022-09-01 14:03 UTC, khelwood requested changes
I commented a piece of code; also some tests are failing

2022-09-06 12:42 UTC, seenanair approved these changes
Looks good.

2022-09-06 12:42 UTC, seenanair commented on src/components/visiumQC/CDNAMeasurementQC.tsx
> +  comments: CommentFieldsFragment[];
Same here - Good to mention 'Concentration' comments

2022-09-06 12:49 UTC, seenanair reviewed
All looking good apart from vertical alignment issue.

2022-09-07 08:50 UTC, seenanair approved these changes

2022-09-14 12:38 UTC, merged