Slide costing field added to Visium QC Slide Processing
sanger/stan-client pull request #232
Opened 2022-10-26 17:30 UTC by seenanair

Slide costing field added to Slide Processing in Visium QC
 - Options are Faculty, SGP
 - Mandatory field

2022-11-01 09:39 UTC, khelwood requested changes

2022-11-01 09:39 UTC, khelwood commented on src/pages/VisiumQC.tsx
> +          debugger;
debugger;

2022-11-02 11:52 UTC, seenanair commented on src/pages/VisiumQC.tsx
> +          debugger;
Done 👍

2022-11-02 13:21 UTC, khelwood approved these changes

2022-11-02 14:00 UTC, merged