Added Probe Hybridisation Xenium , Xenium Analyser operation dates to dashboard
sanger/stan-client pull request #509
Opened 2023-12-11 16:11 UTC by seenanair

2023-12-12 09:28 UTC, sabrine33 approved these changes

2023-12-14 13:35 UTC, khelwood requested changes

2023-12-14 13:35 UTC, khelwood commented on src/lib/services/workProgressService.ts
> +    debugger;
debugger

2023-12-14 13:35 UTC, khelwood commented on src/lib/services/workProgressService.ts
> +    debugger;
debugger

2023-12-14 13:35 UTC, khelwood commented on src/lib/services/workProgressService.ts
> +    debugger;
debugger

2023-12-14 14:35 UTC, khelwood approved these changes

2023-12-14 16:38 UTC, merged