download and redirect
sanger/stan-client pull request #663
Opened 2024-05-01 11:01 UTC by sabrine33

update release file link in the history page to redirect the user to release options page and download the file

2024-05-03 12:03 UTC, khelwood requested changes
My reading of this is that it downloads the release-file and then redirects to the release-options page. I think it should just take you to the release-options page.

2024-05-07 09:34 UTC, sabrine33 commented
@khelwood I thought that is what is been requested, may be worth double check with @KatyTaylor

2024-05-09 10:17 UTC, khelwood approved these changes

2024-05-09 10:24 UTC, merged

2024-05-09 10:24 UTC, sabrine33 commented
merged into devel